export const SET_IS_FETCHING_COMMENTS = 'SET_IS_FETCHING_COMMENTS';
export const SET_COMMENTS = 'SET_COMMENTS';
export const POST_PET_COMMENT = 'POST_PET_COMMENT';
export const POST_PET_AD_COMMENT = 'POST_PET_AD_COMMENT';