export const ADD_FOUND_PET = 'ADD_FOUND_PET';
export const POST_FOUND_PET = 'POST_FOUND_PET';
export const SET_ADDING_FOUND_PET = 'SET_ADDING_FOUND_PET';
export const FETCH_PETS = 'FETCH_PETS';
export const SET_FETCHING_PETS = 'SET_FETCHING_PETS';
export const SET_PETS = 'SET_PETS';

export const POST_PET_AD = 'POST_PET_AD';
export const SET_ADDING_PET_AD = 'SET_ADDING_LOST_PET';

export const FETCH_LOST_PETS = 'FETCH_LOST_PETS';
export const SET_FETCHING_LOST_PETS = 'SET_FETCHING_LOST_PETS';
export const SET_LOST_PETS = 'SET_LOST_PETS';
export const ADD_LOST_PET = 'ADD_LOST_PET';

export const FETCH_ADOPTING_PETS = 'FETCH_ADOPTING_PETS';
export const SET_FETCHING_ADOPTING_PETS = 'SET_FETCHING_ADOPTING_PETS';
export const SET_ADOPTING_PETS = 'SET_ADOPTING_PETS';
export const ADD_ADOPTING_PET = 'ADD_ADOPTING_PET';

export const FETCH_PET_COMMENTS = 'FETCH_PET_COMMENTS';
export const FETCH_PET_AD_COMMENTS = 'FETCH_PET_AD_COMMENTS';